/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kandil
 */
public class Iwish1 extends javax.swing.JFrame {

    /**
     * Creates new form Iwish1
     */
    public Iwish1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogFriendItem = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        labelProdNameFI = new javax.swing.JLabel();
        btnContributeFI = new javax.swing.JButton();
        txtContributionAmountFI = new javax.swing.JTextField();
        scrollPaneProdDescFI = new javax.swing.JScrollPane();
        textPaneProdDescFI = new javax.swing.JTextPane();
        labelPriceFI = new javax.swing.JLabel();
        DialogAvailableItem = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        labelProdNameAI = new javax.swing.JLabel();
        btnAddAI = new javax.swing.JButton();
        scrollPaneProdDescAI = new javax.swing.JScrollPane();
        textPaneProdDescAI = new javax.swing.JTextPane();
        labelPriceAI = new javax.swing.JLabel();
        DialogMyItem = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        labelProdNameMI = new javax.swing.JLabel();
        scrollPaneProdDescMI = new javax.swing.JScrollPane();
        textPaneProdDescMI = new javax.swing.JTextPane();
        labelPriceMI = new javax.swing.JLabel();
        progBarMoney = new javax.swing.JProgressBar();
        DialogFriendRequest = new javax.swing.JDialog();
        labelRequest = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        mainPane = new javax.swing.JTabbedPane();
        panelFriends = new javax.swing.JPanel();
        scrollPanelFriends = new javax.swing.JScrollPane();
        listFriends = new javax.swing.JList<>();
        scrollPanelFriendWish = new javax.swing.JScrollPane();
        listFriendWish = new javax.swing.JList<>();
        labelFriendList = new javax.swing.JLabel();
        labelFriendWishList = new javax.swing.JLabel();
        btnRemoveFriend = new javax.swing.JButton();
        btnSendRequest = new javax.swing.JButton();
        btnFriendEmail = new javax.swing.JTextField();
        labelNewFriend = new javax.swing.JLabel();
        panelMyWishList = new javax.swing.JPanel();
        scrollPanelMyWish = new javax.swing.JScrollPane();
        listMyWish = new javax.swing.JList<>();
        labelMyWish = new javax.swing.JLabel();
        scrollPanelAvailableItems = new javax.swing.JScrollPane();
        listAvailableItems = new javax.swing.JList<>();
        labelAvailableItems = new javax.swing.JLabel();
        btnRemoveItem = new javax.swing.JButton();
        panelFriendRequests = new javax.swing.JPanel();
        scrollPanelFriendRequests = new javax.swing.JScrollPane();
        listFriendRequests = new javax.swing.JList<>();
        panelNotifications = new javax.swing.JPanel();
        regsPane = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtUserRegs = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPwRegs = new javax.swing.JTextField();
        btnRegs = new javax.swing.JButton();
        btnNewLog = new javax.swing.JButton();
        loginPane = new javax.swing.JPanel();
        txtUsrLog = new javax.swing.JTextField();
        txtPwLog = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnNewRegs = new javax.swing.JButton();

        labelProdNameFI.setText("<product name>");

        btnContributeFI.setText("contribute");

        txtContributionAmountFI.setText("jTextField1");

        scrollPaneProdDescFI.setViewportView(textPaneProdDescFI);

        labelPriceFI.setText("<price>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(scrollPaneProdDescFI, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtContributionAmountFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(btnContributeFI)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(labelProdNameFI)
                        .addGap(93, 93, 93)
                        .addComponent(labelPriceFI)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProdNameFI)
                    .addComponent(labelPriceFI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneProdDescFI, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContributeFI)
                    .addComponent(txtContributionAmountFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout DialogFriendItemLayout = new javax.swing.GroupLayout(DialogFriendItem.getContentPane());
        DialogFriendItem.getContentPane().setLayout(DialogFriendItemLayout);
        DialogFriendItemLayout.setHorizontalGroup(
            DialogFriendItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogFriendItemLayout.setVerticalGroup(
            DialogFriendItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelProdNameAI.setText("<product name>");

        btnAddAI.setText("Add To My List");

        scrollPaneProdDescAI.setViewportView(textPaneProdDescAI);

        labelPriceAI.setText("<price>");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(scrollPaneProdDescAI, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelProdNameAI)
                        .addGap(93, 93, 93)
                        .addComponent(labelPriceAI)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnAddAI)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProdNameAI)
                    .addComponent(labelPriceAI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneProdDescAI, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAddAI)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout DialogAvailableItemLayout = new javax.swing.GroupLayout(DialogAvailableItem.getContentPane());
        DialogAvailableItem.getContentPane().setLayout(DialogAvailableItemLayout);
        DialogAvailableItemLayout.setHorizontalGroup(
            DialogAvailableItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogAvailableItemLayout.setVerticalGroup(
            DialogAvailableItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelProdNameMI.setText("<product name>");

        scrollPaneProdDescMI.setViewportView(textPaneProdDescMI);

        labelPriceMI.setText("<price>");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(scrollPaneProdDescMI, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(labelProdNameMI)
                        .addGap(93, 93, 93)
                        .addComponent(labelPriceMI)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(progBarMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProdNameMI)
                    .addComponent(labelPriceMI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneProdDescMI, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(progBarMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout DialogMyItemLayout = new javax.swing.GroupLayout(DialogMyItem.getContentPane());
        DialogMyItem.getContentPane().setLayout(DialogMyItemLayout);
        DialogMyItemLayout.setHorizontalGroup(
            DialogMyItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogMyItemLayout.setVerticalGroup(
            DialogMyItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelRequest.setText("<Folan> Wants to be your friend");

        btnAccept.setText("Accept");

        btnDecline.setText("Decline");

        javax.swing.GroupLayout DialogFriendRequestLayout = new javax.swing.GroupLayout(DialogFriendRequest.getContentPane());
        DialogFriendRequest.getContentPane().setLayout(DialogFriendRequestLayout);
        DialogFriendRequestLayout.setHorizontalGroup(
            DialogFriendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogFriendRequestLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(btnAccept)
                .addGap(46, 46, 46)
                .addComponent(btnDecline)
                .addGap(123, 123, 123))
            .addGroup(DialogFriendRequestLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(labelRequest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogFriendRequestLayout.setVerticalGroup(
            DialogFriendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogFriendRequestLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DialogFriendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnDecline))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPane.setPreferredSize(new java.awt.Dimension(320, 375));

        listFriends.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Friend 1", "Friend 2", "Friend 3", "Friend 4", "Friend 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPanelFriends.setViewportView(listFriends);

        listFriendWish.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPanelFriendWish.setViewportView(listFriendWish);

        labelFriendList.setText("Friend List");

        labelFriendWishList.setText("Folan wants");

        btnRemoveFriend.setText("Remove");
        btnRemoveFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFriendActionPerformed(evt);
            }
        });

        btnSendRequest.setText("Send Request");

        btnFriendEmail.setText("jTextField1");

        labelNewFriend.setText("Add new friend");

        javax.swing.GroupLayout panelFriendsLayout = new javax.swing.GroupLayout(panelFriends);
        panelFriends.setLayout(panelFriendsLayout);
        panelFriendsLayout.setHorizontalGroup(
            panelFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFriendsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveFriend)
                    .addComponent(btnSendRequest)
                    .addComponent(labelNewFriend)
                    .addGroup(panelFriendsLayout.createSequentialGroup()
                        .addGroup(panelFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnFriendEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPanelFriends, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(labelFriendList, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(107, 107, 107)
                        .addGroup(panelFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFriendWishList)
                            .addComponent(scrollPanelFriendWish, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFriendsLayout.setVerticalGroup(
            panelFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFriendsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFriendList)
                    .addComponent(labelFriendWishList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPanelFriendWish, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(scrollPanelFriends))
                .addGap(18, 18, 18)
                .addComponent(btnRemoveFriend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNewFriend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFriendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendRequest)
                .addContainerGap())
        );

        mainPane.addTab("Friends", panelFriends);
        panelFriends.getAccessibleContext().setAccessibleName("friends");
        panelFriends.getAccessibleContext().setAccessibleDescription("");

        listMyWish.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item 1", "item 2", "item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPanelMyWish.setViewportView(listMyWish);

        labelMyWish.setText("My Wish List");

        listAvailableItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPanelAvailableItems.setViewportView(listAvailableItems);

        labelAvailableItems.setText("Avaiable Items");

        btnRemoveItem.setText("Remove ");

        javax.swing.GroupLayout panelMyWishListLayout = new javax.swing.GroupLayout(panelMyWishList);
        panelMyWishList.setLayout(panelMyWishListLayout);
        panelMyWishListLayout.setHorizontalGroup(
            panelMyWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMyWishListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMyWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelMyWish, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMyWish)
                    .addComponent(btnRemoveItem))
                .addGap(76, 76, 76)
                .addGroup(panelMyWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAvailableItems)
                    .addComponent(scrollPanelAvailableItems, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMyWishListLayout.setVerticalGroup(
            panelMyWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMyWishListLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelMyWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMyWish)
                    .addComponent(labelAvailableItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMyWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMyWishListLayout.createSequentialGroup()
                        .addComponent(scrollPanelMyWish, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnRemoveItem))
                    .addComponent(scrollPanelAvailableItems, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        mainPane.addTab("My Wishlist", panelMyWishList);

        listFriendRequests.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPanelFriendRequests.setViewportView(listFriendRequests);

        javax.swing.GroupLayout panelFriendRequestsLayout = new javax.swing.GroupLayout(panelFriendRequests);
        panelFriendRequests.setLayout(panelFriendRequestsLayout);
        panelFriendRequestsLayout.setHorizontalGroup(
            panelFriendRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelFriendRequests, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        panelFriendRequestsLayout.setVerticalGroup(
            panelFriendRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelFriendRequests, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        mainPane.addTab("Friend Requests", panelFriendRequests);

        javax.swing.GroupLayout panelNotificationsLayout = new javax.swing.GroupLayout(panelNotifications);
        panelNotifications.setLayout(panelNotificationsLayout);
        panelNotificationsLayout.setHorizontalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        panelNotificationsLayout.setVerticalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        mainPane.addTab("Gifts Notifications", panelNotifications);

        getContentPane().add(mainPane, "card2");
        mainPane.getAccessibleContext().setAccessibleName("Friends");

        regsPane.setPreferredSize(new java.awt.Dimension(320, 375));

        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });

        txtPwRegs.setText("jTextField5");

        btnRegs.setText("Create an account");

        btnNewLog.setText("Already have an account? Login now");

        javax.swing.GroupLayout regsPaneLayout = new javax.swing.GroupLayout(regsPane);
        regsPane.setLayout(regsPaneLayout);
        regsPaneLayout.setHorizontalGroup(
            regsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regsPaneLayout.createSequentialGroup()
                .addGroup(regsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regsPaneLayout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addComponent(btnNewLog))
                    .addGroup(regsPaneLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnRegs)))
                .addGap(43, 43, 43))
            .addGroup(regsPaneLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(regsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEmail)
                    .addComponent(txtUserRegs)
                    .addComponent(txtLastname)
                    .addComponent(txtPwRegs)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        regsPaneLayout.setVerticalGroup(
            regsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regsPaneLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUserRegs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPwRegs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRegs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNewLog)
                .addGap(14, 14, 14))
        );

        getContentPane().add(regsPane, "card3");

        txtUsrLog.setText("jTextField1");
        txtUsrLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsrLogActionPerformed(evt);
            }
        });

        txtPwLog.setText("jTextField1");

        btnLogin.setText("Log in");

        btnNewRegs.setText("create a new account");

        javax.swing.GroupLayout loginPaneLayout = new javax.swing.GroupLayout(loginPane);
        loginPane.setLayout(loginPaneLayout);
        loginPaneLayout.setHorizontalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewRegs)
                    .addComponent(btnLogin)
                    .addComponent(txtPwLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsrLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        loginPaneLayout.setVerticalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(txtUsrLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtPwLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnNewRegs)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(loginPane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtUsrLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsrLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsrLogActionPerformed

    private void btnRemoveFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFriendActionPerformed
        // TODO add your handling code here:
        DialogFriendItem.setBounds(100, 100, 500, 500);
        DialogFriendItem.setVisible(true);
    }//GEN-LAST:event_btnRemoveFriendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iwish1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iwish1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iwish1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iwish1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iwish1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogAvailableItem;
    private javax.swing.JDialog DialogFriendItem;
    private javax.swing.JDialog DialogFriendRequest;
    private javax.swing.JDialog DialogMyItem;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAddAI;
    private javax.swing.JButton btnContributeFI;
    private javax.swing.JButton btnDecline;
    private javax.swing.JTextField btnFriendEmail;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewLog;
    private javax.swing.JButton btnNewRegs;
    private javax.swing.JButton btnRegs;
    private javax.swing.JButton btnRemoveFriend;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelAvailableItems;
    private javax.swing.JLabel labelFriendList;
    private javax.swing.JLabel labelFriendWishList;
    private javax.swing.JLabel labelMyWish;
    private javax.swing.JLabel labelNewFriend;
    private javax.swing.JLabel labelPriceAI;
    private javax.swing.JLabel labelPriceFI;
    private javax.swing.JLabel labelPriceMI;
    private javax.swing.JLabel labelProdNameAI;
    private javax.swing.JLabel labelProdNameFI;
    private javax.swing.JLabel labelProdNameMI;
    private javax.swing.JLabel labelRequest;
    private javax.swing.JList<String> listAvailableItems;
    private javax.swing.JList<String> listFriendRequests;
    private javax.swing.JList<String> listFriendWish;
    private javax.swing.JList<String> listFriends;
    private javax.swing.JList<String> listMyWish;
    private javax.swing.JPanel loginPane;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JPanel panelFriendRequests;
    private javax.swing.JPanel panelFriends;
    private javax.swing.JPanel panelMyWishList;
    private javax.swing.JPanel panelNotifications;
    private javax.swing.JProgressBar progBarMoney;
    private javax.swing.JPanel regsPane;
    private javax.swing.JScrollPane scrollPaneProdDescAI;
    private javax.swing.JScrollPane scrollPaneProdDescFI;
    private javax.swing.JScrollPane scrollPaneProdDescMI;
    private javax.swing.JScrollPane scrollPanelAvailableItems;
    private javax.swing.JScrollPane scrollPanelFriendRequests;
    private javax.swing.JScrollPane scrollPanelFriendWish;
    private javax.swing.JScrollPane scrollPanelFriends;
    private javax.swing.JScrollPane scrollPanelMyWish;
    private javax.swing.JTextPane textPaneProdDescAI;
    private javax.swing.JTextPane textPaneProdDescFI;
    private javax.swing.JTextPane textPaneProdDescMI;
    private javax.swing.JTextField txtContributionAmountFI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtPwLog;
    private javax.swing.JTextField txtPwRegs;
    private javax.swing.JTextField txtUserRegs;
    private javax.swing.JTextField txtUsrLog;
    // End of variables declaration//GEN-END:variables
}
